spring:
  application:
    name: Arquitetura Spring
  jpa:
    show-sql: true
  main:
    lazy-initialization: false

app:
  config:
    variavel: Testando mensagem de string
    valor3: 150
    falador: se comunica bem